sbk_mongodb:
  image: 'sbk_mongodb:1.0.0'
  environment:
    - MONGODB_ADMIN_USER=sbkroot
    - MONGODB_ADMIN_PASS=sbkroot1234
    - MONGODB_APPLICATION_DATABASE=development
    - MONGODB_APPLICATION_USER=sbkuser
    - MONGODB_APPLICATION_PASS=sbkuser1234
  ports:
    - '5500:27017'
  privileged: true
  volumes:
    - '~/environment/springbootkotlin/mongodb/data:/data/db'
  restart: always

